version: "3.3"

services:

  flask:
    image: flask-dev
    ports:
      - 5000:5000
    volumes:
      - ./src:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    volumes:
      - ./.mysql_data:/var/lib/mysql